version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    cooldown:
      default-days: 7
    directory: /
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
