name: Release

on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Clone Larkspur
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/install-node
        name: Install Node.js 24
        with:
          node-version: 24

      - name: Install zsh
        run: sudo apt-get install -y ncurses-term zsh

      - name: Check code
        run: ./bin/larkspur check

      - name: Test
        run: ./bin/larkspur test all

      - name: Publish to npm
        run: npm stage publish --provenance --access public
