name: Run a Larkspur task

on:
  workflow_call:
    inputs:
      flags:
        description: Flags to pass to the Larkspur task
        type: string
      node-version:
        description: The Node.js version to use
        required: true
        type: number
      task:
        description: The Larkspur task to run
        required: true
        type: string

jobs:
  run-task:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Clone Larkspur
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/install-node
        name: Install Node.js ${{ inputs.node-version }}
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run larkspur ${{ inputs.task }}
        run: ./bin/larkspur ${{ inputs.task }} ${{ inputs.flags }}
