name: Verify

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: Check
    uses: ./.github/workflows/run-task.yml
    with:
      node-version: 24
      task: check

  package:
    name: Package
    needs: check
    uses: ./.github/workflows/run-task.yml
    with:
      node-version: 24
      task: package verify

  test:
    name: Test (v${{ matrix.node-version }})
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]
    steps:
      - name: Clone Larkspur
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/install-node
        name: Install Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install zsh
        run: sudo apt-get install -y ncurses-term zsh

      - name: Run unit tests
        run: ./bin/larkspur test unit

      - name: Run integration tests
        run: ./bin/larkspur test integration

      - name: Run property tests
        run: ./bin/larkspur test property --runs 1000
