name: Verify Publishing

run-name: Verify Larkspur v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: A published Larkspur version
        required: true
        type: string

permissions:
  contents: read

jobs:
  verify:
    name: Verify (v${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]
    steps:
      - name: Clone Larkspur
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/install-node
        name: Install Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Verify larkspur@${{ inputs.version }}
        run: ./bin/larkspur publish verify --version ${{ inputs.version }}
