name: Verify

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/run-task.yml
    with:
      node-version: 24
      task: check

  build:
    name: Build
    needs: check
    uses: ./.github/workflows/run-task.yml
    with:
      node-version: 24
      task: build

  test:
    name: Test (v${{ matrix.node-version }})
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]
    steps:
      - name: Clone Larkspur
        uses: actions/checkout@v7

      - uses: ./.github/actions/install-node
        name: Install Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install zsh
        run: sudo apt-get install -y ncurses-term zsh

      - name: Run unit tests
        run: ./bin/larkspur test unit

      - name: Run integration tests
        run: ./bin/larkspur test integration

      - name: Run property tests
        run: ./bin/larkspur test property --runs 1000
